# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: test

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: '1.20'
          check-latest: true
          cache: false

      - name: Setup policy-tester
        run: |
          go install github.com/sigstore/policy-controller/cmd/tester
          # Rename it as policy-tester for clarity.
          mv "$(which tester)" "$(dirname "$(which tester)")/policy-tester"

      - run: |
          go test -v ./...
